### ISSUE TITLE
clock display is weird with long interval (-i) times.

### ISSUE THREAD

**Issue by lindes** [lindes/ttyload#1]
When run with, for example, -i 120, the clock updates along the bottom of the graph are... weird.  E.g. one big string at the right side, which contains:

^^^^^^11:59^^^^12:1

[Reported by @Telofy on twitter](https://twitter.com/Telofy/status/310828029632983041) (thank you, @Telofy!):

"when I use a large -i (e.g., -i 120), the time labels look weird"

**Comment by lindes** [comment]
Fixed in my local tree.  Running -i 120 for a while to confirm before submitting; expect it soon.

**Comment by Telofy** [comment]
Thankies!

**Comment by lindes** [comment]
You're welcome!  Fixed; new version 0.5.3 released.  Commit e9cf5ae0d6ec5be5d1446e1a3bf8bf2ca307f57f pushed.
